services:
  - type: web
    name: my-vite-app
    env: static
    staticPublishPath: dist
    buildCommand: npm install && npm run build
    routes:
      - source: /.*
        destination: /index.html
